server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://47.104.204.228:3306/gulimall_sms
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用8.0以上的mysql驱动，驱动名要加cj

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #mapper-locations: classpath:/mapper/**/*.xml
  #classpath之后带*表示扫描当前项目以及jar包里面的classpath
  #不带*表示只扫描当前项目下的classpath
  global-config:
    db-config:
      id-type: auto
