server:
  port: 20000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  thymeleaf:
    cache: false
  redis:
    host: 47.104.204.228
    port: 6379
  session:
    store-type: redis

ribbon:
  read-timeout: 5000
  connect-timeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true