server:
  port: 25000
spring:
  application:
    name: gulimall-seckill
  session:
    store-type: redis
  redis:
    host: 47.104.204.228
    port: 6379
    jedis:
      pool:
        max-active: 20
    timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
#  #sleuth+zipkin链路追踪
#  zipkin:
#    base-url: http://47.104.204.228:9411/
#    discovery-client-enabled: false #关闭服务发现功能
#    sender:
#      type: web   #以http的方式发送数据
#  sleuth:
#    sampler:
#      probability: 1 #设置抽样采集率为100%，默认为0.1，即10%

  rabbitmq:
    virtual-host: /
    host: 47.104.204.228
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
