server:
  port: 25000
spring:
  application:
    name: gulimall-seckill
  session:
    store-type: redis
  redis:
    host: 47.104.204.228
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
