server:
  port: 9000
spring:
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.104.204.228:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 47.104.204.228
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    template:
      mandatory: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
#        prefetch: 1
  session:
    store-type: redis
  redis:
    host: 47.104.204.228
    port: 6379
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

my-thread-pool:
  config:
    core-pool-size: 20
    max-pool-size: 500
    keep-alive-time: 10
    queue-capacity: 100000

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

#seata:
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#  tx-service-group: gulimall_group