server:
  port: 11000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.104.204.228:3306/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  application:
    name: gulimall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 47.104.204.228
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

feign:
  sentinel:
    enabled: true


logging:
  level:
    com.dzy.gulimall.ware: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

#seata:
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#  tx-service-group: gulimall_group

